# Copyright (c) sebba.dev
#
# This source code is licensed under the GPLv3 license found in the
# license.md file in the root directory of this source tree.

[install.scopes]
# Setup private vichava npm registry scope, use .env.local file to set the credentials (bun package manager required)
"@vichava" = {username = "$REGISTRY_USER", password = "$REGISTRY_PWD", url = "https://npm.pkg.github.com"}